// frontend-svelte/src/routes/dnssec/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { config } from '#lib/config/index.ts';
	import { queryAllNodes, type NodeRow } from '#lib/node-pool.ts';
	import { visitorIP, visitorIsIPv6 } from '#lib/visitor-ip.svelte.ts';
	import { INPUT_CLASS, BUTTON_CLASS } from '#lib/ui-classes.ts';
	import { Button } from '#lib/components/ui/button/index.js';
	import { Input } from '#lib/components/ui/input/index.js';
	import PageTitle from '#lib/components/PageTitle.svelte';

	interface DNSSECResult {
		domain: string;
		enabled: boolean;
		valid: boolean;
		has_rrsig: boolean;
		has_dnskey: boolean;
		has_ds: boolean;
		algorithm: number;
		key_tag: number;
		signer_name: string;
		validation: string;
		duration: number;
	}

	/** 三栈平铺（旧站顺序：双栈 → IPv4 → IPv6） */
	const nodes = [...config.APIBaseURL.DualStack, ...config.APIBaseURL.IPv4, ...config.APIBaseURL.IPv6];
	const canonicalUrl = `${config.siteUrl}dnssec`;

	let tmpDomain = $state('www.zakoflare.com');
	let loading = $state(false);
	let rows = $state<NodeRow<DNSSECResult>[]>([]);

	function getValidationClass(r: DNSSECResult): string {
		if (r.valid) return 'status-success';
		if (r.has_dnskey || r.has_rrsig) return 'status-warning';
		return 'status-error';
	}

	function formatDuration(ms?: number): string {
		return typeof ms === 'number' && isFinite(ms) ? ms.toFixed(2) + ' ms' : '-';
	}

	async function checkDNSSEC() {
		const domain = tmpDomain.trim();
		if (!domain) return;

		loading = true;
		rows = nodes.map((node) => ({ label: node.label ?? '', loading: true }));

		await queryAllNodes<DNSSECResult>(
			nodes,
			(id) => `/middleware/${id}/dnssec/${encodeURIComponent(domain)}`,
			rows,
			(e) => (e instanceof Error ? e.message : '请求失败')
		);
		loading = false;
	}

	onMount(() => {
		const domainParam = page.url.searchParams.get('domain');
		if (domainParam) {
			tmpDomain = domainParam;
			checkDNSSEC();
		}
	});
</script>

<svelte:head>
	<title>DNSSEC查询 | 域名DNSSEC验证检测 | {config.siteName}</title>
	<link rel="canonical" href={canonicalUrl} />
	<meta
		name="description"
		content="专业的DNSSEC查询工具,支持域名DNSSEC验证检测,检查域名是否启用DNSSEC签名,验证DNSKEY、RRSIG、DS记录链式信任关系,检测域名DNS数据完整性和真实性,防止DNS欺骗和中间人攻击,保障域名解析安全"
	/>
	<meta
		name="keywords"
		content="dnssec查询,dnssec验证,dnskey,rrsig,ds记录,域名安全,链式信任,dns欺骗防护,域名解析安全,dns签名验证"
	/>
	<meta property="og:title" content="DNSSEC查询工具 - 域名DNSSEC验证与安全检测" />
	<meta
		property="og:description"
		content="DNSSEC验证检测工具,检查域名DNSSEC签名状态,验证DNSKEY、RRSIG、DS记录链式信任关系"
	/>
	<meta property="og:image" content={`${config.siteUrl}favicon.svg`} />
	<meta property="og:type" content="website" />
	{@html `<script type="application/ld+json">${JSON.stringify({
		'@context': 'https://schema.org',
		'@type': 'WebApplication',
		name: 'DNSSEC验证查询工具',
		description:
			'专业的DNSSEC验证查询工具，检测域名DNSSEC签名状态，验证DNSKEY、RRSIG、DS记录链式信任关系，保障域名解析安全。',
		url: canonicalUrl,
		applicationCategory: 'DeveloperApplication',
		operatingSystem: 'Web',
		offers: { '@type': 'Offer', price: '0', priceCurrency: 'CNY' },
		provider: { '@type': 'Organization', name: config.siteName }
	})}</script>`}
</svelte:head>

<PageTitle h1="DNSSEC 验证查询" sub="检测域名 DNSSEC 签名状态和链式信任验证" />

<div class="content">
	<div class="one-line">
		<Input
			class={INPUT_CLASS}
			bind:value={tmpDomain}
			placeholder="请输入域名（如：example.com）"
			onkeydown={(e) => e.key === 'Enter' && checkDNSSEC()}
		/>
		<Button class={BUTTON_CLASS} disabled={loading} onclick={checkDNSSEC}>
			{loading ? '验证中…' : '验证'}
		</Button>
	</div>

	{#if rows.some((r) => r.data)}
		<div class="result-section">
			<table class="result-table">
				<thead>
					<tr>
						<th class="table-header">DNS 服务器</th>
						<th class="table-header">DNSSEC</th>
						<th class="table-header">DNSKEY</th>
						<th class="table-header">RRSIG</th>
						<th class="table-header">DS</th>
						<th class="table-header">验证结果</th>
						<th class="table-header">耗时</th>
					</tr>
				</thead>
				<tbody>
					{#each rows as row (row.label)}
						{#if row.data}
							<tr>
								<td class="table-label">{row.label}</td>
								<td class="table-value">
									<span class="status-code {row.data.enabled ? 'status-success' : 'status-error'}">
										{row.data.enabled ? '已启用' : '未启用'}
									</span>
								</td>
								<td class="table-value">
									<span class="status-code {row.data.has_dnskey ? 'status-success' : 'status-error'}">
										{row.data.has_dnskey ? '有' : '无'}
									</span>
								</td>
								<td class="table-value">
									<span class="status-code {row.data.has_rrsig ? 'status-success' : 'status-error'}">
										{row.data.has_rrsig ? '有' : '无'}
									</span>
								</td>
								<td class="table-value">
									<span class="status-code {row.data.has_ds ? 'status-success' : 'status-error'}">
										{row.data.has_ds ? '有' : '无'}
									</span>
								</td>
								<td class="table-value">
									<span class="status-code {getValidationClass(row.data)}">
										{row.data.valid ? '验证通过' : '验证失败'}
									</span>
								</td>
								<td class="table-value">{formatDuration(row.data.duration)}</td>
							</tr>
						{:else if row.loading}
							<tr>
								<td class="table-label">{row.label}</td>
								<td class="table-value" colspan="6">加载中...</td>
							</tr>
						{:else if row.error}
							<tr>
								<td class="table-label">{row.label}</td>
								<td class="table-value error-text" colspan="6">{row.error}</td>
							</tr>
						{:else}
							<tr>
								<td class="table-label">{row.label}</td>
								<td class="table-value" colspan="6">-</td>
							</tr>
						{/if}
					{/each}
				</tbody>
			</table>
		</div>
	{/if}

	<blockquote>
		DNSSEC 原理介绍即将上线<br />
		DNSSEC 通过 DNSKEY、RRSIG、DS 记录为 DNS 数据提供完整性验证，防止 DNS 欺骗攻击。<br />
		如果显示 "验证失败"，可能原因：域名未配置 DNSSEC、DNSKEY 密钥不匹配、DS 记录缺失等。<br />
		<a href="/dns" target="_blank">DNS 解析查询</a> | <a href="/whois" target="_blank">Whois 查询</a><br />
		访客IP: {visitorIP() || '获取中...'}，您的网络{visitorIsIPv6() ? 'IPv6' : 'IPv4'}优先<br />
	</blockquote>
</div>

<style>
	.result-table .table-label {
		width: 180px;
	}
</style>

// frontend-ssr/app/pages/dnssec.vue
<script setup lang="ts">
import { useMiddlewareFetch } from '../../utils/middleware';
import { ref, onMounted, computed, nextTick } from 'vue'
import { useRoute } from 'vue-router'
import { config } from '../../config/index'
import { isIPv6 } from 'is-ip'


const route = useRoute()

useHead({
  title: `DNSSEC查询 | 域名DNSSEC验证检测 | ${config.siteName}`,
  meta: [
    { name: 'description', content: '专业的DNSSEC查询工具,支持域名DNSSEC验证检测,检查域名是否启用DNSSEC签名,验证DNSKEY、RRSIG、DS记录链式信任关系,检测域名DNS数据完整性和真实性,防止DNS欺骗和中间人攻击,保障域名解析安全' },
    { name: 'keywords', content: 'dnssec查询,dnssec验证,dnskey,rrsig,ds记录,域名安全,链式信任,dns欺骗防护,域名解析安全,dns签名验证' },
    { property: 'og:title', content: 'DNSSEC查询工具 - 域名DNSSEC验证与安全检测' },
    { property: 'og:description', content: 'DNSSEC验证检测工具,检查域名DNSSEC签名状态,验证DNSKEY、RRSIG、DS记录链式信任关系' },
    { property: 'og:image', content: config.siteUrl + 'favicon.svg' },
    { property: 'og:type', content: 'website' },
  ],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebApplication',
        name: 'DNSSEC验证查询工具',
        description: '专业的DNSSEC验证查询工具，检测域名DNSSEC签名状态，验证DNSKEY、RRSIG、DS记录链式信任关系，保障域名解析安全。',
        url: config.siteUrl + 'dnssec',
        applicationCategory: 'DeveloperApplication',
        operatingSystem: 'Web',
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'CNY'
        },
        provider: {
          '@type': 'Organization',
          name: config.siteName
        }
      })
    }
  ]
})

interface DNSSECResult {
  domain: string
  enabled: boolean
  valid: boolean
  has_rrsig: boolean
  has_dnskey: boolean
  has_ds: boolean
  algorithm: number
  key_tag: number
  signer_name: string
  validation: string
  duration: number
}

interface ServerResult {
  label: string
  loading: boolean
  error?: string
  data?: DNSSECResult
}

const tmpDomain = ref('www.zakoflare.com')
const loading = ref(false)
const serverResults = ref<ServerResult[]>([])
const userIP = ref('')
// 查询序号：连续点击时旧查询的结果不允许写入新查询的结果表
let queryId = 0

const apiList = [
  ...config.APIBaseURL.DualStack,
  ...config.APIBaseURL.IPv4,
  ...config.APIBaseURL.IPv6
]

const dnssecFetches = apiList.map((server) => {
  const url = computed(() => "/middleware/" + server.id + "/dnssec/" + encodeURIComponent(tmpDomain.value.trim()))
  const { data, error, execute } = useMiddlewareFetch<DNSSECResult>(url, {
    immediate: false,
    watch: false,
  })
  return { label: server.label, data, error, execute }
})

function initServerResults() {
  serverResults.value = apiList.map((server) => ({
    label: server.label,
    loading: false,
  }))
}

async function checkDNSSEC() {
  const domain = tmpDomain.value.trim()
  if (!domain) return

  loading.value = true

  const id = ++queryId

  serverResults.value.forEach((result) => {
    result.loading = true
    result.data = undefined
  })

  const promises = dnssecFetches.map(async (fetch, index) => {
    try {
      await fetch.execute()
      if (id !== queryId) return
      const result = serverResults.value[index]
      if (result) {
        // execute() 不会抛错，失败以 error.value 为准（否则故障节点渲染成 '-'）
        if (fetch.error.value) {
          result.error = (fetch.error.value as any)?.message || '请求失败'
        } else {
          result.data = fetch.data.value
        }
      }
    } catch (err) {
      console.error(err)
      const result = serverResults.value[index]
      if (result) {
        result.error = (err as any)?.message || '请求失败'
      }
    } finally {
      const result = serverResults.value[index]
      if (result && id === queryId) {
        result.loading = false
      }
    }
  })

  Promise.allSettled(promises).finally(function () {
    if (id === queryId) {
      loading.value = false
    }
  })
}

function getValidationClass(result: DNSSECResult): string {
  if (result.valid) return 'status-success'
  if (result.has_dnskey || result.has_rrsig) return 'status-warning'
  return 'status-error'
}

function formatDuration(ms?: number): string {
  return typeof ms === 'number' && isFinite(ms) ? ms.toFixed(2) + ' ms' : '-'
}

onMounted(() => {
  initServerResults()
  getUserIP()
  const domainParam = route.query.domain as string
  if (domainParam) {
    tmpDomain.value = domainParam
    checkDNSSEC()
  }
})

async function getUserIP() {
  try {
    userIP.value = await $fetch<string>(config.DualStackAPI)
  } catch {
    // 获取失败保持为空，避免未处理的 Promise 拒绝
  }
  return userIP.value
}
</script>

<template>
  <div class="title">
    <header>
      <h1>DNSSEC 验证查询</h1>
      <p>检测域名 DNSSEC 签名状态和链式信任验证</p>
    </header>
  </div>
  <div class="content">
    <div class="one-line">
      <el-input
        v-model="tmpDomain"
        placeholder="请输入域名（如：example.com）"
      />
      <el-button
        @click="checkDNSSEC()"
        type="primary"
        :loading="loading"
      >
        验证
      </el-button>
    </div>



    <div class="result-section" v-if="serverResults.some(r => r.data)">
      <table class="result-table">
        <thead>
          <tr>
            <th class="table-header">DNS 服务器</th>
            <th class="table-header">DNSSEC</th>
            <th class="table-header">DNSKEY</th>
            <th class="table-header">RRSIG</th>
            <th class="table-header">DS</th>
            <th class="table-header">验证结果</th>
            <th class="table-header">耗时</th>
          </tr>
        </thead>
        <tbody>
          <template v-for="(server, index) in serverResults" :key="index">
            <tr v-if="server.data">
              <td class="table-label">{{ server.label }}</td>
              <td class="table-value">
                <span :class="server.data.enabled ? 'status-success' : 'status-error'" class="status-code">
                  {{ server.data.enabled ? '已启用' : '未启用' }}
                </span>
              </td>
              <td class="table-value">
                <span :class="server.data.has_dnskey ? 'status-success' : 'status-error'" class="status-code">
                  {{ server.data.has_dnskey ? '有' : '无' }}
                </span>
              </td>
              <td class="table-value">
                <span :class="server.data.has_rrsig ? 'status-success' : 'status-error'" class="status-code">
                  {{ server.data.has_rrsig ? '有' : '无' }}
                </span>
              </td>
              <td class="table-value">
                <span :class="server.data.has_ds ? 'status-success' : 'status-error'" class="status-code">
                  {{ server.data.has_ds ? '有' : '无' }}
                </span>
              </td>
              <td class="table-value">
                <span :class="getValidationClass(server.data)" class="status-code">
                  {{ server.data.valid ? '验证通过' : '验证失败' }}
                </span>
              </td>
              <td class="table-value">{{ formatDuration(server.data.duration) }}</td>
            </tr>
            <tr v-else-if="server.loading">
              <td class="table-label">{{ server.label }}</td>
              <td class="table-value" colspan="6">加载中...</td>
            </tr>
            <tr v-else-if="server.error">
              <td class="table-label">{{ server.label }}</td>
              <td class="table-value error-text" colspan="6">{{ server.error }}</td>
            </tr>
            <tr v-else-if="!server.data">
              <td class="table-label">{{ server.label }}</td>
              <td class="table-value" colspan="6">-</td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>

    <blockquote>
      DNSSEC 原理介绍即将上线<br/>
      DNSSEC 通过 DNSKEY、RRSIG、DS 记录为 DNS 数据提供完整性验证，防止 DNS 欺骗攻击。<br/>
      如果显示 "验证失败"，可能原因：域名未配置 DNSSEC、DNSKEY 密钥不匹配、DS 记录缺失等。<br/>
      <a href="/dns" target="_blank">DNS 解析查询</a> | <a href="/whois" target="_blank">Whois 查询</a><br/>
      访客IP: {{ userIP || '获取中...' }}，您的网络{{ isIPv6(userIP) ? 'IPv6' : 'IPv4' }}优先<br/>
    </blockquote>
  </div>
</template>

<style scoped>
@import "../style.css";
@import "../../assets/css/tool-common.css";

.el-menu--horizontal > .el-menu-item:nth-child(1) {
  margin-right: auto;
}

.result-table .table-label {
  width: 180px;
}

.error-text {
  color: #F56C6C;
}
</style>

<style>
:root {
  --el-color-primary: #299764;
}
html.dark {
  --el-color-primary: #299764;
}
.el-icon{
  font-size: 1.3em;
}
</style>
