// frontend-ssr/app/pages/location.vue
<script setup lang="ts">
import { ref, onMounted, computed, nextTick, watch } from 'vue';
import { isIPv6 } from 'is-ip';
import {config} from '../../config/index';
import { useMiddlewareFetch } from '../../utils/middleware';
import { CircleCheckFilled, CircleCloseFilled } from '@element-plus/icons-vue';
import { useRoute } from 'vue-router'
import { highlightCode } from '../../utils/shiki'
import { isIPv4 } from '../../utils/tools';
const route = useRoute();
const loading = ref(false);

useHead({
  title: `IPv6/IPv4地址查询工具 | IP归属地定位 | ${config.siteName}`,
  meta: [
    { name: 'description', content: '专业的IPv6/IPv4地址查询工具,支持IPv4和IPv6地址归属地查询,提供BiliBili Live、GeoCN、IP2Region、Maxmind等多种数据源对比,精确定位IP地理位置、运营商信息,支持中国大陆及境外地址查询,助力IPv6普及与应用' },
    { name: 'keywords', content: 'ipv6地址查询,ipv4地址查询,ip归属地,ip地理位置,ip定位,运营商查询,ipv6归属地,ipv4归属地,maxmind,ip2region,geocn' },
    { property: 'og:title', content: `IPv6/IPv4地址归属地查询工具 - ${config.siteName}` },
    { property: 'og:description', content: '多数据源IP地址归属地查询,支持IPv4和IPv6,提供地理位置、运营商等详细信息' },
    { property: 'og:image', content: config.siteUrl + 'favicon.svg' },
    { property: 'og:type', content: 'website' },
  ],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebApplication',
        name: 'IPv6/IPv4地址归属地查询工具',
        description: '专业的IPv6/IPv4地址归属地查询工具，支持BiliBili Live、GeoCN、IP2Region、Maxmind、纯真社区库等多数据源对比，精确定位IP地理位置、运营商信息。',
        url: config.siteUrl + 'ipv6',
        applicationCategory: 'DeveloperApplication',
        operatingSystem: 'Web',
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'CNY'
        },
        provider: {
          '@type': 'Organization',
          name: config.siteName
        }
      })
    }
  ]
});
interface IPLocationType {
  bilibili?: any;
  ip?: string;
  geocn?: any;
  ip2region?: any;
  ip2location?: any;
  ip2location_asn?: any;
  maxmind_asn?: any;
  maxmind_city?: any;
  qqwry?: any;
  [key: string]: any;
}
const code = `
# 请勿用于商业用途，仅供个人测试学习之用，请遵守中国法律法规
# 查询本机外网 IPv4 地址
curl ${config.v4OnlyAPI}

# 查询本机外网 IPv6 地址
curl ${config.v6OnlyAPI}

# 测试网络是 IPv4 还是 IPv6 访问优先 
# (访问 IPv4/IPv6 双栈站点，如果返回 IPv6 地址，则 IPv6 访问优先)
curl ${config.DualStackAPI}
`.trim();
const html = ref('');
const apiList = config.IPLocationAPI
const currentApiIndex = ref(0)
const backendID = computed(() => apiList[currentApiIndex.value]?.id || '')
const ipAddress = ref('');
const IPLocation = ref<IPLocationType>({});
const UserIP = ref('');
const error = ref('')
const locationUrl = computed(() => "/middleware/" + backendID.value + "/location/" + encodeURIComponent(ipAddress.value));

const { data: locationData, error: locationError, execute: executeLocation } = useMiddlewareFetch<IPLocationType>(locationUrl, {
  immediate: false,
  watch: false,
});

watch(locationData, (newData) => {
  if (newData) {
    IPLocation.value = newData;
    loading.value = false;
    error.value = '';
  }
});

watch(locationError, async (newError) => {
  if (newError) {
    console.error('Error fetching IP location:', newError);
    if (currentApiIndex.value < apiList.length - 1) {
      const nextIndex = currentApiIndex.value + 1
      error.value = `${(newError as any).message || '请求失败'}，正在重试 ${apiList[nextIndex]?.label || ''}...`
      currentApiIndex.value = nextIndex
      await nextTick()
      executeLocation()
    } else {
      error.value = '请求失败，请检查网络或稍后重试'
      loading.value = false;
    }
  }
});

function locateIP(IP: string){
  currentApiIndex.value = 0
  ipAddress.value = IP;
  error.value = ''
  loading.value = true;
  nextTick(() => {
    executeLocation();
  });
}

onMounted(async () => {
  html.value = await highlightCode(code, 'bash')
  const urlParam = route.query.ip;
  if (urlParam) {
    ipAddress.value = urlParam as string;
    locateIP(urlParam as string);
  }else{
    $fetch<string>(config.DualStackAPI).then(
      function(data) {
        ipAddress.value = data;

        UserIP.value = data;
      }
    ).catch(
      function(error) {
        console.error('Error fetching IP address:', error);
      }
    );

  }
});
</script>
<template>
  <div class="title">
    <header>
      <h1>IPv6/IPv4地址归属地查询</h1>
      <p>极简的IPv6地址查询工具，致力于普及 IPv6</p>
    </header>
  </div>
  <div class="content">
    <div class="one-line">
      <el-input 
        v-model="ipAddress" 
        placeholder="请输入IP地址" 
      />
      <el-button 
        @click="locateIP(ipAddress)" 
        type="primary" 
        :loading="loading"
      
      >
        查询
      </el-button>
    </div>
    <div v-if="error" class="error-message">
      {{ error }}
    </div>
    <div class="location">
      <div class="ip-info" style="height: 40px;">
        <b>IP</b>&nbsp;<span>{{ ipAddress }}</span>
      </div>
      <div v-if="IPLocation" class="result-section">
          <table class="result-table">
            <tbody>
              <tr v-if="IPLocation.bilibili && (IPLocation.bilibili.administrative_area || IPLocation.bilibili.city)">
                <td class="table-label">bilibili Live接口</td>
                <td class="table-value">
                  <span>
                    {{ IPLocation.bilibili?.country }}&nbsp;{{ IPLocation.bilibili?.administrative_area }}&nbsp;{{ IPLocation.bilibili?.city }}
                  </span>
                </td>
                <td class="table-value">
                  <span>
                    {{ IPLocation.bilibili?.isp }}
                  </span>
                </td>
              </tr>
              <tr v-if="IPLocation.ip2region && typeof IPLocation.ip2region === 'object' && (IPLocation.ip2region.administrative_area || IPLocation.ip2region.city)">
                <td class="table-label">IP2Region</td>
                <td class="table-value">{{ IPLocation.ip2region?.country }}&nbsp;{{ IPLocation.ip2region?.administrative_area }}&nbsp;{{ IPLocation.ip2region?.city }}</td>
                <td class="table-value">{{ IPLocation.ip2region?.isp }}</td>
              </tr>
              <tr v-if="IPLocation.ip2location && typeof IPLocation.ip2location === 'object' && (IPLocation.ip2location.administrative_area || IPLocation.ip2location.city)">
                <td class="table-label">IP2Location</td>
                <td class="table-value">{{ IPLocation.ip2location?.country }}&nbsp;{{ IPLocation.ip2location?.administrative_area }}&nbsp;{{ IPLocation.ip2location?.city }}</td>
                <td class="table-value">{{ IPLocation.ip2location_asn?.as }}</td>
              </tr>
              <tr v-if="IPLocation.geocn && (IPLocation.geocn.administrative_area || IPLocation.geocn.city || IPLocation.geocn.district)">
                <td class="table-label">GeoCN(仅中国大陆)</td>
                <td class="table-value">{{ IPLocation.geocn?.administrative_area }}&nbsp;{{ IPLocation.geocn?.city }}&nbsp;{{ IPLocation.geocn?.district }}</td>
                <td class="table-value">{{ IPLocation.geocn?.isp }}&nbsp;{{IPLocation.geocn?.type}}</td>
              </tr>
              <tr v-if="IPLocation.maxmind_city && IPLocation.maxmind_asn && (IPLocation.maxmind_city.country || IPLocation.maxmind_city.city)">
                <td class="table-label">Maxmind GEOLite2 City</td>
                <td class="table-value">{{ IPLocation.maxmind_city?.country }}&nbsp;{{ IPLocation.maxmind_city?.administrative_area }}&nbsp;{{ IPLocation.maxmind_city?.city }}</td>
                <td class="table-value">{{ IPLocation.maxmind_asn?.org }}</td>
              </tr>
              <tr v-if="IPLocation.qqwry && (IPLocation.qqwry.country || IPLocation.qqwry.administrative_area || IPLocation.qqwry.city)">
                <td class="table-label">纯真社区库</td>
                <td class="table-value">{{ IPLocation.qqwry?.country }}&nbsp;{{ IPLocation.qqwry?.administrative_area }}&nbsp;{{ IPLocation.qqwry?.city }}</td>
                <td class="table-value">{{ IPLocation.qqwry?.isp }}</td>
              </tr>
              <tr v-if="IPLocation.dbip_city && (IPLocation.dbip_city.administrative_area || IPLocation.dbip_city.city)">
                <td class="table-label">DB-IP City</td>
                <td class="table-value">{{ IPLocation.dbip_city?.country }}&nbsp;{{ IPLocation.dbip_city?.administrative_area }}&nbsp;{{ IPLocation.dbip_city?.city }}</td>
                <td class="table-value">{{IPLocation.dbip_asn?.org}}</td>
              </tr>
            </tbody>
          </table>
        </div>
    </div>
    <div style="font-size: 1.5em;">
      <h3 v-if="isIPv6(UserIP)"><el-icon><CircleCheckFilled style="color: lightgreen;"/></el-icon>您的网络IPv6优先</h3>
      <h3 v-else-if="isIPv4(UserIP)"><el-icon><CircleCloseFilled style="color: red;"/></el-icon>您的网络IPv4优先</h3>
    </div>
    <blockquote>
      精度参照表：<br>
      中国大陆:BiliBili Live > GeoCN > IP2Region > 纯真社区库 > Maxmind GEOLite2 City ≈ DB-IP<br>
      中国大陆 IPv6 地址: BiliBili Live > GeoCN > IP2Region > Maxmind GEOLite2 City ≈ DB-IP > 纯真社区库<br>
      境外及港澳台地址: Maxmind GEOLite2 City ≈ DB-IP > BiliBili Live >  > IP2Region > 纯真社区库<br>
      
      手机默认开启 IPv6，宽带开启 IPv6 请自行搜索<br>
      访客IP: {{UserIP}}，<span v-if="isIPv4(UserIP)">您的网络IPv4优先</span><span v-else-if="isIPv6(UserIP)">您的网络IPv6优先</span>
    </blockquote>

    <div v-html="html"></div>

    </div>



</template>
<style scoped>
@import "../style.css";
@import "../../assets/css/tool-common.css";
</style>
<style>
@import "../style.css";
:root {
  --el-color-primary: #3EAF7C;
}
.el-icon{
  font-size: 1.3em;
}
.el-menu--horizontal > .el-menu-item:nth-child(1) {
  margin-right: auto;
}

.el-input {
  width: 420px;
  height: 50px;
  font: 1.3em sans-serif;
  margin-right: 10px;
}

.el-button {
  width: 165px;
  height: 50px;
  font: 1.3em sans-serif;
}

.result-section {
  margin-top: 30px;
}

.result-table {
  width: 100%;
  border-collapse: collapse;
  background: #fff;
  border: 1px solid #dcdfe6;
}
html.dark .result-table {
  width: 100%;
  border-collapse: collapse;
  background: #2e2d2d;
  border: 1px solid #2e2e2e;
}
.result-table thead tr {
  background-color: #c0c4cc;
}
html.dark .result-table thead tr {
    background: #2e2d2d;
}

.result-table .table-header {
  padding: 12px 15px;
  font-weight: 600;
  color: #303133;
  text-align: left;
  border: 1px solid #dcdfe6;
}
html.dark .result-table .table-header {
  padding: 12px 15px;
  font-weight: 600;
  color: #cfcfcf;
  text-align: left;
  border: 1px solid #1a1919;
}

.result-table tbody tr {
  border-bottom: 1px solid #dcdfe6;
}
html.dark .result-table tbody tr {
  border-bottom: 1px solid #1a1919;
}


.result-table tbody tr:last-child {
  border-bottom: none;
}

.result-table tbody tr:hover {
  background-color: #f5f7fa;
}
html.dark .result-table tbody tr:hover {
  background-color: #393a3a;
}

.result-table .table-label {
  padding: 12px 15px;
  font-weight: 600;
  color: #606266;
  width: 150px;
  text-align: left;
  border: 1px solid #dcdfe6;
}
html.dark .result-table .table-label {
  color: #c0c4cc;
  border: 1px solid #1a1919;
}

.result-table .table-value {
  padding: 12px 15px;
  color: #303133;
  border: 1px solid #dcdfe6;
}
html.dark .result-table .table-value {
  color: #cfcfcf;
  border: 1px solid #1a1919;
}
.valid {
  color: #67C23A;
  font-weight: 600;
}

.expired {
  color: #F56C6C;
  font-weight: 600;
}

.status-code {
  font-weight: 600;
  padding: 4px 12px;
  border-radius: 4px;
}

.status-success {
  color: #67C23A;
  background: #f0f9eb;
}

.status-warning {
  color: #E6A23C;
  background: #fdf6ec;
}

.status-error {
  color: #F56C6C;
  background: #fef0f0;
}

.error-message {
  margin-top: 20px;
  padding: 15px;
  background: #fef0f0;
  color: #F56C6C;
  border-radius: 6px;
  text-align: center;
  font-size: 1.1em;
}

pre {
  background: #f8f9fa;
  padding: 15px;
  border-radius: 6px;
  overflow-x: auto;
  white-space: pre;
  max-width: 100%;
}

pre code {
  font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
  font-size: 0.9em;
  color: #303133;
}
html.dark pre {
  background: #303133;
}

html.dark pre code {
  font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
  color: #f8f9fa;
}



.badge-section {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-top: 20px;
}

.badge-item {
  background: #fff;
  padding: 20px;
  border-radius: 8px;
  border: 1px solid #e4e7ed;
}

.badge-item h4 {
  margin: 0 0 15px 0;
  color: #3EAF7C;
  font-size: 1.2em;
}

.badge-item img {
  display: block;
  margin-bottom: 15px;
  max-width: 200px;
}
</style>

// frontend-svelte/src/routes/location/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import CircleCheckFilled from '#lib/components/icons/CircleCheckFilled.svelte';
	import CircleCloseFilled from '#lib/components/icons/CircleCloseFilled.svelte';
	import { config } from '#lib/config/index.ts';
	import { queryNodePool } from '#lib/node-pool.ts';
	import { visitorIP, visitorIsIPv6 } from '#lib/visitor-ip.svelte.ts';
	import { INPUT_CLASS, BUTTON_CLASS } from '#lib/ui-classes.ts';
	import { Button } from '#lib/components/ui/button/index.js';
	import { Input } from '#lib/components/ui/input/index.js';
	import PageTitle from '#lib/components/PageTitle.svelte';

	let { data } = $props();

	const apiList = config.IPLocationAPI;
	const canonicalUrl = `${config.siteUrl}ipv6`;

	let ipAddress = $state('');
	let ipLocation = $state<any>({});
	let error = $state('');
	let loading = $state(false);

	/**
	 * 查询指定 IP 的归属地：IPLocationAPI 里的节点逐个试（内层还会切中间件通道）。
	 *
	 * 说明：访客自己的 IP 有两处用到 —— 底部的「访客IP」与网络优先级提示。
	 * 旧站这两处读的是同一个 ref，且只在**没有** `?ip=` 参数时才去探测；
	 * 这里改用全局共享的 `visitorIP()`（见 #lib/visitor-ip），无论从哪个入口进来都能显示，
	 * 属于顺带修好的一个小空白（旧站带 `?ip=` 打开时那两处是空的）。
	 */
	async function locateIP(ip: string) {
		const target = ip.trim();
		ipAddress = target;
		error = '';
		if (!target) {
			error = '请输入IP地址';
			return;
		}

		loading = true;
		const outcome = await queryNodePool<any>(
			apiList,
			(id) => `/middleware/${id}/location/${encodeURIComponent(target)}`,
			{ onRetry: (msg) => (error = msg) }
		);
		loading = false;

		if (outcome.ok) {
			ipLocation = outcome.data ?? {};
			error = '';
		} else {
			ipLocation = {};
			error = '请求失败，请检查网络或稍后重试';
		}
	}

	// 带 `?ip=` 进来就直接查（旧站同样在 onMounted 里这么干）
	$effect(() => {
		const ip = page.url.searchParams.get('ip');
		if (ip) locateIP(ip);
	});
</script>

<svelte:head>
	<title>IPv6/IPv4地址查询工具 | IP归属地定位 | {config.siteName}</title>
	<link rel="canonical" href={canonicalUrl} />
	<meta
		name="description"
		content="专业的IPv6/IPv4地址查询工具,支持IPv4和IPv6地址归属地查询,提供BiliBili Live、GeoCN、IP2Region、Maxmind等多种数据源对比,精确定位IP地理位置、运营商信息,支持中国大陆及境外地址查询,助力IPv6普及与应用"
	/>
	<meta
		name="keywords"
		content="ipv6地址查询,ipv4地址查询,ip归属地,ip地理位置,ip定位,运营商查询,ipv6归属地,ipv4归属地,maxmind,ip2region,geocn"
	/>
	<meta property="og:title" content={`IPv6/IPv4地址归属地查询工具 - ${config.siteName}`} />
	<meta property="og:description" content="多数据源IP地址归属地查询,支持IPv4和IPv6,提供地理位置、运营商等详细信息" />
	<meta property="og:image" content={`${config.siteUrl}favicon.svg`} />
	<meta property="og:type" content="website" />
	{@html `<script type="application/ld+json">${JSON.stringify({
		'@context': 'https://schema.org',
		'@type': 'WebApplication',
		name: 'IPv6/IPv4地址归属地查询工具',
		description:
			'专业的IPv6/IPv4地址归属地查询工具，支持BiliBili Live、GeoCN、IP2Region、Maxmind、纯真社区库等多数据源对比，精确定位IP地理位置、运营商信息。',
		url: canonicalUrl,
		applicationCategory: 'DeveloperApplication',
		operatingSystem: 'Web',
		offers: { '@type': 'Offer', price: '0', priceCurrency: 'CNY' },
		provider: { '@type': 'Organization', name: config.siteName }
	})}</script>`}
</svelte:head>

<PageTitle h1="IPv6/IPv4地址归属地查询" sub="极简的IPv6地址查询工具，致力于普及 IPv6" />

<div class="content">
	<div class="one-line">
		<Input
			class={INPUT_CLASS}
			bind:value={ipAddress}
			placeholder="请输入IP地址"
			onkeydown={(e) => e.key === 'Enter' && locateIP(ipAddress)}
		/>
		<Button class={BUTTON_CLASS} disabled={loading} onclick={() => locateIP(ipAddress)}>
			{loading ? '查询中…' : '查询'}
		</Button>
	</div>

	{#if error}
		<div class="error-message">{error}</div>
	{/if}

	<div class="location">
		<div class="ip-info" style="height: 40px;">
			<b>IP</b>&nbsp;<span>{ipAddress}</span>
		</div>

		{#if ipLocation}
			<div class="result-section">
				<table class="result-table">
					<tbody>
						{#if ipLocation.bilibili && (ipLocation.bilibili.administrative_area || ipLocation.bilibili.city)}
							<tr>
								<td class="table-label">bilibili Live接口</td>
								<td class="table-value">
									<span>
										{ipLocation.bilibili?.country}&nbsp;{ipLocation.bilibili?.administrative_area}&nbsp;{ipLocation
											.bilibili?.city}
									</span>
								</td>
								<td class="table-value"><span>{ipLocation.bilibili?.isp}</span></td>
							</tr>
						{/if}
						{#if ipLocation.ip2region && typeof ipLocation.ip2region === 'object' && (ipLocation.ip2region.administrative_area || ipLocation.ip2region.city)}
							<tr>
								<td class="table-label">IP2Region</td>
								<td class="table-value">
									{ipLocation.ip2region?.country}&nbsp;{ipLocation.ip2region
										?.administrative_area}&nbsp;{ipLocation.ip2region?.city}
								</td>
								<td class="table-value">{ipLocation.ip2region?.isp}</td>
							</tr>
						{/if}
						{#if ipLocation.ip2location && typeof ipLocation.ip2location === 'object' && (ipLocation.ip2location.administrative_area || ipLocation.ip2location.city)}
							<tr>
								<td class="table-label">IP2Location</td>
								<td class="table-value">
									{ipLocation.ip2location?.country}&nbsp;{ipLocation.ip2location
										?.administrative_area}&nbsp;{ipLocation.ip2location?.city}
								</td>
								<td class="table-value">{ipLocation.ip2location_asn?.as}</td>
							</tr>
						{/if}
						{#if ipLocation.geocn && (ipLocation.geocn.administrative_area || ipLocation.geocn.city || ipLocation.geocn.district)}
							<tr>
								<td class="table-label">GeoCN(仅中国大陆)</td>
								<td class="table-value">
									{ipLocation.geocn?.administrative_area}&nbsp;{ipLocation.geocn?.city}&nbsp;{ipLocation
										.geocn?.district}
								</td>
								<td class="table-value">{ipLocation.geocn?.isp}&nbsp;{ipLocation.geocn?.type}</td>
							</tr>
						{/if}
						{#if ipLocation.maxmind_city && ipLocation.maxmind_asn && (ipLocation.maxmind_city.country || ipLocation.maxmind_city.city)}
							<tr>
								<td class="table-label">Maxmind GEOLite2 City</td>
								<td class="table-value">
									{ipLocation.maxmind_city?.country}&nbsp;{ipLocation.maxmind_city
										?.administrative_area}&nbsp;{ipLocation.maxmind_city?.city}
								</td>
								<td class="table-value">{ipLocation.maxmind_asn?.org}</td>
							</tr>
						{/if}
						{#if ipLocation.qqwry && (ipLocation.qqwry.country || ipLocation.qqwry.administrative_area || ipLocation.qqwry.city)}
							<tr>
								<td class="table-label">纯真社区库</td>
								<td class="table-value">
									{ipLocation.qqwry?.country}&nbsp;{ipLocation.qqwry?.administrative_area}&nbsp;{ipLocation
										.qqwry?.city}
								</td>
								<td class="table-value">{ipLocation.qqwry?.isp}</td>
							</tr>
						{/if}
						{#if ipLocation.dbip_city && (ipLocation.dbip_city.administrative_area || ipLocation.dbip_city.city)}
							<tr>
								<td class="table-label">DB-IP City</td>
								<td class="table-value">
									{ipLocation.dbip_city?.country}&nbsp;{ipLocation.dbip_city
										?.administrative_area}&nbsp;{ipLocation.dbip_city?.city}
								</td>
								<td class="table-value">{ipLocation.dbip_asn?.org}</td>
							</tr>
						{/if}
					</tbody>
				</table>
			</div>
		{/if}
	</div>

	<div style="font-size: 1.5em;">
		{#if visitorIsIPv6()}
			<h3>
				<CircleCheckFilled class="ak-inline-icon text-[lightgreen]" />
				您的网络IPv6优先
			</h3>
		{:else if visitorIP()}
			<h3>
				<CircleCloseFilled class="ak-inline-icon text-[red]" />
				您的网络IPv4优先
			</h3>
		{/if}
	</div>

	<blockquote>
		精度参照表：<br />
		中国大陆:BiliBili Live &gt; GeoCN &gt; IP2Region &gt; 纯真社区库 &gt; Maxmind GEOLite2 City ≈ DB-IP<br />
		中国大陆 IPv6 地址: BiliBili Live &gt; GeoCN &gt; IP2Region &gt; Maxmind GEOLite2 City ≈ DB-IP &gt; 纯真社区库<br
		/>
		境外及港澳台地址: Maxmind GEOLite2 City ≈ DB-IP &gt; BiliBili Live &gt; IP2Region &gt; 纯真社区库<br />
		手机默认开启 IPv6，宽带开启 IPv6 请自行搜索<br />
		访客IP: {visitorIP()}，<span
			>{visitorIsIPv6() ? '您的网络IPv6优先' : visitorIP() ? '您的网络IPv4优先' : ''}</span
		>
	</blockquote>

	<div>{@html data.highlighted}</div>
</div>

<style>
	/* 表格列宽与旧站一致（结果表本身的样子在 site.css 里） */
	.result-table .table-label {
		width: 200px;
	}
</style>
